### ISSUE TITLE
Urgent need for another download link

### ISSUE THREAD

**Issue by akira-l** [ZihaoWang-CV/CAMP_iccv19#11]
Could anyone share this data with me by another link or download manner?
The current link always fails after downloading for serval hours.
![image](https://user-images.githubusercontent.com/9478838/184618343-fe83b053-87ae-425f-a3de-d28739560af3.png)

I have already changed three servers to download this data, and it always fails.

**Comment by LinjieMu** [comment]
Hello, can you solve this problem now? 
That link is invalid now. 
Do you find another download link? 
Thanks!

**Comment by ZihaoWang-CV** [comment]
Thank you for your interest.
Could you try to manually extract the features from MSCOCO/Flickr, following https://github.com/kuanghuei/SCAN#data-pre-processing-optional
That works for me.
