### ISSUE TITLE
Why in your code did not have negative sample pairs? Can you explain your hardest negative binary cross-entropy loss in the code? Thank you very much!

### ISSUE THREAD

**Issue by haoopan** [ZihaoWang-CV/CAMP_iccv19#4]

**Comment by ZihaoWang-CV** [comment]
Sorry for my late reply.

When sample a batch of positive pairs (e.g., 128 positive pairs), we would compute the pair-wise similarity matrix of all those 128*128 pairs.  Thus, the diagonal of the matrix would the the similarities of all positive pairs while the other positions in the matrix would be the similarities of negative pairs.
