### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by idejie** [ZihaoWang-CV/CAMP_iccv19#5]
Hello, great code but I had some doubts.

I noticed that the CUDA is used in  [your model](https://github.com/ZihaoWang-CV/CAMP_iccv19/blob/82e0d8419190f7d1d415250dabb5ea741d5ec720/model.py#L351).
```python
drive_num = torch.cuda.device_count()
if keep == "words":
    cur_s = s.unsqueeze(0).expand(drive_num, -1, -1, -1)
elif keep == "regions":
    cur_im = im.unsqueeze(0).expand(drive_num, -1, -1, -1)
```
I tried to re-product the experiments on the dataset Flickr30K with the steps which you provided in `README` but failed with the error `CUDA out of memory`.
```python
/data1/yangdejie/anaconda3/envs/reid/lib/python3.7/site-packages/torch/nn/functional.py:1625: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/data1/yangdejie/projects/CAMP/model.py:629: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  clip_grad_norm(self.params, self.grad_clip)
Traceback (most recent call last):
  File "../../train.py", line 211, in <module>
    main()
  File "../../train.py", line 74, in main
    train(opt, train_loader, model, epoch, val_loader, tb_logger)
  File "../../train.py", line 112, in train
    model.train_emb(*train_data)
  File "/data1/yangdejie/projects/CAMP/model.py", line 626, in train_emb
    loss.backward()
  File "/data1/yangdejie/anaconda3/envs/reid/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data1/yangdejie/anaconda3/envs/reid/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 10.76 GiB total capacity; 9.04 GiB already allocated; 231.44 MiB free; 9.71 GiB reserved in total by PyTorch)
```
My environment:
```
# GPU: 2080ti(11G) x 4
pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
torchvision               0.7.0                py37_cu101    pytorch
```

So could you provide your requirements?
And what is the size of GPU memory or the size of the batch that can be successful to conduct the experiments?

**Comment by ZihaoWang-CV** [comment]
Thanks for your interest in our project!

The GPU usage of our experiments is mentioned here: https://github.com/ZihaoWang-CV/CAMP_iccv19/issues/1#issuecomment-564404704

> Since the image features are pre-extracted from the Faster R-CNN, it only costs around 12GB/GPU memories and 1.1s/batch while distributed running on 16 TITAN XP GPUs. (or ~28GB/GPU, 0.8s/batch on 8 V100 GPUs).

>Our code is based on the implementation of VSE++ and SCAN, we compute 128*(128/num_devices) pairs on each GPU and gather the final score matrix(1281281) on GPU 0 to compute the final loss. This could be simply implemented by expanding the text feature with shape (batch_size, word_num, dim) to (device_num, batch_size, word_num, dim) and passing it through the nn.DataParallel.

We recommend reducing the batch size from 128 to 64 on 2080ti.  The smaller batch size may cause a slight performance drop.

**Comment by idejie** [comment]
Thank you a lot for your answer!

I reduced the batch size from 128 to 5.

First, I tried to run it  on one GPU(2080TI) with the script you provided:
```
cd ./experiments/f30k_gate_fusion
python python -u ../../train.py --config ./config_finetune.yaml
```
But It still occurred with a problem `RuntimeError: CUDA out of memory.`

```python
Traceback (most recent call last):
  File "../../train.py", line 211, in <module>
    main()
  File "../../train.py", line 78, in main
    rsum = validate(opt, val_loader, model, tb_logger)
  File "../../train.py", line 153, in validate
    (i2t_r1, i2t_r5, i2t_r10, i2t_medr, i2t_meanr), (t2i_r1, t2i_r5, t2i_r10, t2i_medr, t2i_meanr) = i2t(img_embs, cap_embs, cap_masks, measure=opt.measure, model=model)
  File "/data1/yangdejie/projects/CAMP/evaluation.py", line 297, in i2t
    mask=Variable(torch.ByteTensor(masks)).cuda())
  File "/data1/yangdejie/anaconda3/envs/reid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1/yangdejie/projects/CAMP/model.py", line 390, in forward
    scores = self.sim(cur_im, cur_s, keep=keep, mask=cur_mask)
  File "/data1/yangdejie/anaconda3/envs/reid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1/yangdejie/anaconda3/envs/reid/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data1/yangdejie/anaconda3/envs/reid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data1/yangdejie/projects/CAMP/fusion_module.py", line 500, in forward
    weighted_v1, attn_1 = qkv_attention(q2, k1, v1)
  File "/data1/yangdejie/projects/CAMP/fusion_module.py", line 42, in qkv_attention
    scores = torch.matmul(query, key.transpose(-2, -1)) / sqrt(d_k)
RuntimeError: CUDA out of memory. Tried to allocate 3.43 GiB (GPU 0; 10.76 GiB total capacity; 7.97 GiB already allocated; 1.92 GiB free; 8.02 GiB reserved in total by PyTorch)
```

**Comment by ZihaoWang-CV** [comment]
Sorry for my late reply.
If the OOM error occurs during validation, you could try to reduce the `bs ` variable at line 287 in `evaluation.py` . This variable controls how many images would be used in a batch to calculate the similarity score with all captions in the validation set.

Also, you could try to use the `cross-attention` setting to train the baseline model first (its architecture is different from the SCAN model). It still has a strong baseline result and requires less GPU memory. The training and validating periods are very fast.
