### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by HYY0508** [ZihaoWang-CV/CAMP_iccv19#7]
Hi, thanks for your paper and repo.
I'am interested in running your code but when I try to download the data
e.g.
wget https://scanproject.blob.core.windows.net/scan-data/vocab.zip

I obtain:
Resolving scanproject.blob.core.windows.net (scanproject.blob.core.windows.net)... failed: Unknown Host. .
wget: unable to resolve host address 'scanproject.blob.core.windows.net'

Is this a temporary issue or the data are no more available?

Thanks

**Comment by ZihaoWang-CV** [comment]
The data links are restored by the original author: 
https://github.com/kuanghuei/SCAN/issues/40
